apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge
  labels:
    {{- include "forge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.forge.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "forge.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "forge.labels" . | nindent 8 }}
    spec:
      containers:
        - name: forge
          image: "{{ .Values.forge.image }}"
          imagePullPolicy: {{ .Values.forge.imagePullPolicy | default "IfNotPresent" }}
          env:
            {{- include "chutes.commonEnv" . | nindent 12 }}
            - name: DOCKER_PULL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: docker-pull
                  key: username
            - name: DOCKER_PULL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docker-pull
                  key: password
            - name: STORAGE_DRIVER
              value: "vfs"
            - name: BUILDAH_FORMAT
              value: "docker"
            - name: BUILDAH_ISOLATION
              value: "chroot"
            - name: PYTHONPATH
              value: "/forge"
            - name: BUILDAH_PARALLEL_PULL
              value: "1"
            - name: BUILDAH_LAYERS_PARALLEL_PULL
              value: "1"
            - name: BUILDAH_PULL_JOBS
              value: "16"
            - name: BUILDAH_PROGRESS
              value: plain
            - name: BUILDAH_PARALLEL_PUSH
              value: "1"
            - name: BUILDAH_LAYERS_PARALLEL_PUSH
              value: "1"
            - name: BUILDAH_PUSH_JOBS
              value: "16"
          securityContext:
            privileged: true
            capabilities:
              add:
                - SETUID
                - SETGID
                - SYS_ADMIN
            allowPrivilegeEscalation: true
          resources:
            {{- toYaml .Values.forge.resources | nindent 12 }}
          {{- with .Values.forge.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.forge.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.forge.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.forge.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.forge.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
