apiVersion: apps/v1
kind: Deployment
metadata:
  name: graval-worker
  labels:
    {{- include "gravalWorker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gravalWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "gravalWorker.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gravalWorker.labels" . | nindent 8 }}
    spec:
      {{- with .Values.gravalWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gravalWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gravalWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      runtimeClassName: nvidia-container-runtime
      containers:
        - name: graval-worker
          image: "{{ .Values.gravalWorker.image }}"
          imagePullPolicy: {{ .Values.gravalWorker.imagePullPolicy }}
          command: ["poetry", "run", "taskiq", "worker", "api.graval_worker:broker", "--workers", "1", "--max-async-tasks", "4"]
          env:
            {{- include "chutes.commonEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.gravalWorker.resources | nindent 12 }}
